export const ADD_TASK = "ADD_TASK";
export const EDIT_TASK = "EDIT_TASK";
export const DELETE_TASK = "DELETE_TASK";
export const FOUND_BAD_WORD = "FOUND_BAD_WORD";
export const MONTHLY_TASKS_LOADED = "MONTHLY_TASKS_LOADED";
export const DAILY_TASKS_LOADED = "DAILY_TASKS_LOADED";
export const SET_CURRENT_DATE = "SET_CURRENT_DATE";

export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
export const SET_CALENDAR_MODE = 'SET_CALENDAR_MODE';